### ISSUE TITLE
No licences file!

### ISSUE THREAD

**Issue by apohllo** [kwrobel-nlp/krnnt#12]

**Comment by pmarcis** [comment]
Hi! Is there an update on the license? What can this tool be used for? Without a license, it is unclear whether it can or cannot be used...

**Comment by apohllo** [comment]
AFAIK the license is LGPL.

**Comment by pmarcis** [comment]
Thanks, but that is not official information, right? The license, if there is one, should be found within the repository itself. Otherwise, it is the same as having no license at all...

**Comment by djstrong** [comment]
It is licensed under LGPL as it is stated in the README. One file with the license will be enough for you? I really don't want placing it in every source code file (as it should be done).

**Comment by djstrong** [comment]
@pmarcis BTW we have met at EAMT 2016 ;)

**Comment by pmarcis** [comment]
Thanks! I missed the text in the README! One file is enough for me ;)
EAMT in 2016 was in Riga. You have a good memory as I was not presenting anything at EAMT 2016. I was just visiting then. I see (in Google Scholar) that your interests have shifted away from what you presented then.
