### ISSUE TITLE
Dead publication link

### ISSUE THREAD

**Issue by mflis** [kwrobel-nlp/krnnt#13]
https://ltc.amu.edu.pl/book/papers/PolEval1-6.pdf - this address returns 404.

Could you provide active link to publication?

**Comment by djstrong** [comment]
In a couple of days the paper probably will be available at: https://ltc.amu.edu.pl/a2017/book/papers/PolEval1-6.pdf
I have sent request to LTC organizers.

**Comment by djstrong** [comment]
I made the paper available at ResearchGate: https://www.researchgate.net/publication/333566748_KRNNT_Polish_Recurrent_Neural_Network_Tagger
