### ISSUE TITLE
Enable prediction?

### ISSUE THREAD

**Issue by mike-code** [kwrobel-nlp/krnnt#14]
Hi. So I was looking for faster alternative for concraft tagger. If I understand correctly, krnnt can do as much as the predecessor or even more and it's faster which sounds fantastic.

I tried a sample HTTP query "Ten sprzęt jest dosć drogi" where it returned
```
Ten	newline
	ten	adj:sg:nom:m3:pos	disamb
sprzęt	space
	sprzęt	subst:sg:nom:m3	disamb
jest	space
	być	fin:sg:ter:imperf	disamb
dosć	space
	dosć	inf:imperf	disamb
drogi	space
	droga	subst:sg:gen:f	disamb
.	none
	.	interp	disamb
```

as you can see it predicted `drogi` to be a noun instead of an adjective.
How do I make krnnt predict it properly? I'm using docker image and I'm not sure whether it's already a pre-trained image or do I have to train it first each time I run the container?

**Comment by mike-code** [comment]
Sorry for a premature ticket. It was fully my mistake, there was a type "dosć" instead of "dość" (s -> ś). By using proper orthography the results were correct.

**Comment by djstrong** [comment]
Hi, docker version has a trained model.
The speed depends on hardware (GPU or not) and usage.

**Comment by djstrong** [comment]
Unfortunately, I don't. There is no good (if any) automatic spelling corrector for Polish. However, the model could be retrained on data with spelling errors.

**Comment by mike-code** [comment]
And that would probably be the way to go. Thank you so much for such a prompt response. As a side question (doesn't really belong to GH issues), are you aware of any tool that is capable of creating a noun forms out of adjectives/verbs eg. szybki -> szybkość?

**Comment by djstrong** [comment]
You can look at: http://sgjp.pl/leksemy/#148049/szybki (however it is only online version) and Polish Wordnet: http://plwordnet.pwr.wroc.pl/wordnet/8076e4a8-5d15-11e9-bb9d-2bfbb4185fa7

**Comment by mike-code** [comment]
Magnificent. Thank you once again:-)
