### ISSUE TITLE
Pass all arguments as options in krnnt_run

### ISSUE THREAD

**Issue by apohllo** [kwrobel-nlp/krnnt#3]
Current implementation assumes that there are 3 positional arguments, but there are also other arguments in the `krnnt_run` command. Moreover, the input and output are accepted from STDIN and STDOUT.
IMHO it would be better when all the arguments were passed as options (i.e. `-f input_file.txt`, `-d dictionary.pkl`, etc.) since it is much easier to discover problems with the invalid arguments (from the POV of the user).

**Comment by djstrong** [comment]
Python documentation disagrees: https://docs.python.org/3.7/library/optparse.html
Optional arguments can not be required...
